import type { GetServerSideProps, NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import React from "react";
import LoginButton from "../component/LoginButton";
import styles from "../styles/Home.module.css";

const Home: NextPage = (props) => {
	const { data: session } = useSession();

	const [linkDescription, setLinkDescription] = React.useState("");
	const [linkUrl, setLinkUrl] = React.useState("");
	const [linkSlug, setLinkSlug] = React.useState("");

	return (
		<div className={styles.container}>
			<Head>
				<title>PPI One</title>
				{/* <meta name="description" content="Generated by create next app" /> */}
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>
					Welcome to <a>PPI.One</a>
				</h1>

				<LoginButton />
				<br />

				{!!session && (
					<Link href="/links">
						<button>Manage links</button>
					</Link>
				)}
			</main>
		</div>
	);
};

export default Home;
